---
- import_tasks: prepare_dist_pkgs.yml
- name: install agent
  package:
    name: "newrelic-infra"
    state: "{{ nrinfragent_state }}"
  when: nrinfragent_os_name|lower != 'windows'

#- name: install integrations
#  package:
#    name: "{{ item.name }}"
#    state: "{{ item.state }}"
#  with_items: "{{ nrinfragent_integrations }}"
#  when: nrinfragent_os_name|lower != 'windows'
- name: Install Zoookepper
  import_tasks: install_dist_nri-zookeeper.yml
  when:
    - nrinfragent_zookeeper
- name: Install Varnish
  import_tasks: install_dist_nri-varnish.yml
  when:
    - nrinfragent_varnish
- name: Install Redis
  import_tasks: install_dist_nri-redis.yml
  when:
    - nrinfragent_redis
- name: Install postgresql
  import_tasks: install_dist_nri-postgresql.yml
  when:
    - nrinfragent_postgresql
- name: Install nginx
  import_tasks: install_dist_nri-nginx.yml
  when:
    - nrinfragent_nginx
- name: Install mysql
  import_tasks: install_dist_nri-mysql.yml
  when:
    - nrinfragent_mysql
- name: install agent (windows)
  win_chocolatey:
    name: newrelic-infra
    state: "{{ nrinfragent_state }}"
    version: "{{ nrinfragent_choco_version | default(omit) }}"
  when:
    - nrinfragent_os_name|lower == 'windows'

- name: setup agent config
  template:
    src: newrelic-infra.yml.j2
    dest: /etc/newrelic-infra.yml
    mode: 0600
  notify: restart newrelic-infra
  when:
    - nrinfragent_state != "absent"
    - nrinfragent_os_name|lower != 'windows'

- name: setup agent config
  win_template:
    src: newrelic-infra.yml.j2
    dest: '%ProgramFiles%\New Relic\newrelic-infra\newrelic-infra.yml'
  notify: restart newrelic-infra (windows)
  when:
    - nrinfragent_state != "absent"
    - nrinfragent_os_name|lower == 'windows'

- name: setup agent service
  service:
    name: newrelic-infra
    state: "{{ nrinfragent_service_state }}"
    enabled: "{{ nrinfragent_service_enabled }}"
  when:
    - nrinfragent_state != "absent"
    - nrinfragent_os_name|lower != 'windows'

- name: setup agent service
  win_service:
    name: newrelic-infra
    state: "{{ nrinfragent_service_state }}"
    enabled: "{{ nrinfragent_service_enabled }}"
  when:
    - nrinfragent_state != "absent"
    - nrinfragent_os_name|lower == 'windows'
