---
- name: install varnish integration
  package:
    name: "nri-varnish"
    state: "present"

- name: setup varnish config
  template:
    src: varnish-config.yml.j2
    dest: /etc/newrelic-infra/integrations.d/varnish-config.yml
    mode: 0600
  notify: restart newrelic-infra
  when:
    - nrinfragent_state != "absent"
    - nrinfragent_os_name|lower != 'windows'