---
- name: install nginx integration
  package:
    name: "nri-nginx"
    state: "present"

- name: setup nginx config
  template:
    src: nginx-config.yml.j2
    dest: /etc/newrelic-infra/integrations.d/nginx-config.yml
    mode: 0600
  notify: restart newrelic-infra
  when:
    - nrinfragent_state != "absent"
    - nrinfragent_os_name|lower != 'windows'